"""Emit Prometheus alerting rules for the conditions in ``alerting.py``.

The gateway has always served a Prometheus exposition on ``/metrics`` and anyone
scraping it has had no alerting story at all -- only prose in the deployment
docs describing what a Honeycomb user should do. This closes that, and in doing
so it is the evidence that ``alerting.py`` is genuinely backend-neutral rather
than Honeycomb's shape with the labels filed off.

    python -m controlplane.prometheus --out switchboard.rules.yml

Two differences from the Honeycomb emitter are worth noticing, because both of
them are the point:

**The spelling.** This applies ``switchboard_``; the Honeycomb emitter applies
``switchboard.``. Each backend consumes a different export path from the same
gateway, and each path spells the counters its own way. Neither prefix appears
in ``alerting.py``.

**The count.** This emits one rule per condition, four in total. The Honeycomb
emitter folds three of them into a single trigger, because that backend's free
plan allows two triggers per team. That folding is a compromise with a vendor's
pricing, not something Switchboard believes about its own counters, so it lives
in that emitter and not here.

YAML is written by hand rather than with a library. The control plane has no
YAML dependency, the output is a fixed shape with no user-supplied keys, and the
only values interpolated are metric names from a literal tuple in this
repository and prose that is quoted. Adding PyYAML to emit forty lines would be
a poor trade.
"""
import argparse
import os
import sys

from . import alerting

# The Prometheus exposition writes "switchboard_" + name; see ServeHTTP in
# internal/gateway/telemetry.go. The OTLP exporter writes "switchboard." + name
# instead, which is why no prefix is stored in alerting.py.
PREFIX = "switchboard_"

# Long enough that a single scrape gap cannot fire an alert, short enough that
# lost service is not minutes stale. Prometheus evaluates `expr` continuously and
# `for` is how long it must stay true, which is a different mechanism from the
# fixed evaluation windows a hosted backend uses; the condition's own window is
# used as the increase() range instead.
FOR = {alerting.PAGE: "2m", alerting.NOTIFY: "10m"}


def quote(s: str) -> str:
    """YAML double-quoted scalar. Prose here contains colons and apostrophes."""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ") + '"'


def expr(cond: alerting.Condition) -> str:
    """Did this counter move during the window.

    increase() over the condition's own window, rather than a rate: these
    counters are rare events, and a rate turns "one account failed over" into a
    small fraction whose threshold nobody can reason about. Asking whether the
    count went up at all keeps the threshold at the honest value, which is zero.
    """
    return f"increase({PREFIX}{cond.metric}[{cond.window}s]) > 0"


def rule(cond: alerting.Condition) -> list[str]:
    return [
        f"    - alert: {''.join(p.title() for p in cond.key.split('_'))}",
        f"      expr: {expr(cond)}",
        f"      for: {FOR[cond.urgency]}",
        "      labels:",
        "        service: switchboard",
        f"        severity: {cond.urgency}",
        "      annotations:",
        f"        summary: {quote(cond.summary)}",
        f"        description: {quote(cond.detail)}",
    ]


def rules() -> str:
    out = [
        "# Alerting rules for Switchboard, generated by controlplane/prometheus.py.",
        "# Conditions are defined in controlplane/alerting.py; edit them there.",
        "#",
        "# Not alerted, deliberately:",
    ]
    for metric, why in alerting.NOT_ALERTED.items():
        out.append(f"#   {PREFIX}{metric}: {why}")
    out += ["groups:", "  - name: switchboard", "    rules:"]
    for cond in alerting.CONDITIONS:
        out += rule(cond)
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="python -m controlplane.prometheus",
        description="Emit Prometheus alerting rules for a Switchboard gateway.",
    )
    ap.add_argument("--out", help="write here instead of stdout, e.g. switchboard.rules.yml")
    a = ap.parse_args(argv)

    text = rules()
    if a.out:
        with open(a.out, "w") as f:
            f.write(text)
        print(f"wrote {a.out} ({len(alerting.CONDITIONS)} rules)", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
