// Capturing what was asked and what came back, so a request can be replayed.
//
// This is the one place in the gateway that writes prompts and completions to
// disk, and it is off unless someone turns it on. `capture_ttl_seconds` is zero
// by default and zero means the store is never constructed at all, so a default
// deployment does not create the directory, let alone a file in it.
//
// The shape is lifted from idempotency.go rather than invented: same 0700
// directory, same 0600 files, same sweep-on-start that makes a restart a
// compaction, same byte cap with the store refusing rather than truncating. That
// store has been exercised; a second design here would only be a second set of
// failure modes to learn.
//
// What is deliberately not here: any path from a capture record into telemetry.
// Records are written to local disk and never read by the exporters, never
// attached to an Event, and never sent to the control plane. That is what keeps
// the promise in docs/SECURITY.md about product telemetry true as written, and
// confines the consequence of enabling capture to one gateway's own disk for one
// TTL.
package gateway

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"regexp"
	"sync"
	"time"
)

// captureRecord is one request, start to finish, with enough routing context to
// be reconstructed without a database. PolicyVersion is the join key back to the
// signed envelope the control plane keeps forever; with it, the route order that
// produced this outcome is recoverable even if the policy has since rotated.
type captureRecord struct {
	RequestID     string          `json:"request_id"`
	TraceID       string          `json:"trace_id,omitempty"`
	PolicyVersion int64           `json:"policy_version,omitempty"`
	Provider      string          `json:"provider,omitempty"`
	Model         string          `json:"model,omitempty"`
	Attempts      int             `json:"attempts"`
	Status        int             `json:"status"`
	Fault         string          `json:"fault,omitempty"`
	Stored        int64           `json:"stored_unix"`
	Prompt        json.RawMessage `json:"prompt,omitempty"`
	Completion    json.RawMessage `json:"completion,omitempty"`
	// RawPrompt holds a request body that is not valid JSON, as a string, and
	// PromptUnparseable says so. The body is recorded before parsing precisely so
	// a request rejected as malformed can still be examined -- and that was the
	// one case never captured, because json.Marshal validates a json.RawMessage
	// and failed the whole record, losing the status, provider and policy version
	// along with it.
	RawPrompt         string `json:"raw_prompt,omitempty"`
	PromptUnparseable bool   `json:"prompt_unparseable,omitempty"`
	// Text carries the assembled answer for a streamed response, because the
	// frames themselves are not a document. docs/API.md already says a replayed
	// stream is the same answer and not the original timing; a capture is the
	// same bargain.
	Text string `json:"text,omitempty"`
}

// requestID is generated by the gateway, not supplied by a caller, so it cannot
// contain a path. Checked anyway: this value names a file, and the cost of being
// wrong once is a write outside the data directory.
var requestID = regexp.MustCompile(`^[0-9a-f]{32}$`)

type captureStore struct {
	dir      string
	ttl      time.Duration
	limit    int64
	maxBytes int64
	m        *Metrics

	mu    sync.Mutex
	used  int64
	count int
}

// NewCaptureStore prepares the store. Callers construct it only when capture is
// enabled; there is no disabled instance, so a nil store is the off state and
// every call site has to say what it does with one.
func NewCaptureStore(dir string, ttl time.Duration, limit int64, m *Metrics) (*captureStore, error) {
	if err := os.MkdirAll(dir, 0700); err != nil {
		return nil, err
	}
	s := &captureStore{dir: dir, ttl: ttl, limit: limit, maxBytes: captureRecordLimit, m: m}
	entries, _ := os.ReadDir(dir)
	for _, e := range entries {
		i, err := e.Info()
		if err != nil {
			continue
		}
		// Expiry is enforced here rather than only on read, because nothing ever
		// reads these files in the serving path. A capture that is never looked
		// at must still stop existing when its TTL is up, or the TTL is a
		// statement about queries rather than about data on a disk.
		if time.Since(i.ModTime()) > ttl {
			os.Remove(filepath.Join(dir, e.Name()))
			continue
		}
		s.used += i.Size()
		s.count++
	}
	return s, nil
}

func (s *captureStore) path(id string) string {
	return filepath.Join(s.dir, id+".json")
}

// Sweep removes expired records. Called periodically as well as at startup,
// since a gateway that stays up for a week would otherwise hold a week of
// prompts under a one-day TTL.
func (s *captureStore) Sweep() {
	s.mu.Lock()
	defer s.mu.Unlock()
	entries, _ := os.ReadDir(s.dir)
	for _, e := range entries {
		i, err := e.Info()
		if err != nil || time.Since(i.ModTime()) <= s.ttl {
			continue
		}
		if os.Remove(filepath.Join(s.dir, e.Name())) == nil {
			s.used -= i.Size()
			s.count--
		}
	}
}

var errCaptureTooLarge = errors.New("capture record exceeds the per-record limit")

// Write stores one record. It refuses rather than truncates: a half-captured
// prompt reads as a complete one, and a replay built on it would be quietly
// wrong, which is worse than a replay that is plainly missing.
func (s *captureStore) Write(r *captureRecord) error {
	if !requestID.MatchString(r.RequestID) {
		return errors.New("capture: request id is not a 32-character hex string")
	}
	// Moved off the JSON path before marshalling rather than after: an invalid
	// Prompt makes json.Marshal fail, and every error counter in this function
	// lives below that call, so the record vanished without a file, a metric or a
	// log line.
	if len(r.Prompt) > 0 && !json.Valid(r.Prompt) {
		r.RawPrompt, r.PromptUnparseable, r.Prompt = string(r.Prompt), true, nil
	}
	b, err := json.Marshal(r)
	if err != nil {
		s.m.DiskErrors.Add(1)
		return err
	}
	if int64(len(b)) > s.maxBytes {
		s.m.DiskErrors.Add(1)
		return errCaptureTooLarge
	}

	s.mu.Lock()
	defer s.mu.Unlock()
	// Full means full. Evicting to make room would silently delete the oldest
	// evidence at exactly the moment the most is being produced, which is the
	// wrong instinct for a store whose purpose is answering questions about the
	// past. An operator who wants more sets a bigger limit.
	if s.used+int64(len(b)) > s.limit {
		s.m.DiskErrors.Add(1)
		return errors.New("capture store is full")
	}
	existing := int64(0)
	if fi, statErr := os.Stat(s.path(r.RequestID)); statErr == nil {
		existing = fi.Size()
	}
	if err := os.WriteFile(s.path(r.RequestID), b, 0600); err != nil {
		s.m.DiskErrors.Add(1)
		return err
	}
	if existing == 0 {
		s.count++
	}
	s.used += int64(len(b)) - existing
	return nil
}

// Read returns one record, or nil if it is absent or past its TTL. Used by
// tooling rather than by the serving path.
func (s *captureStore) Read(id string) *captureRecord {
	if !requestID.MatchString(id) {
		return nil
	}
	b, err := os.ReadFile(s.path(id))
	if err != nil {
		return nil
	}
	var r captureRecord
	if json.Unmarshal(b, &r) != nil {
		return nil
	}
	if time.Since(time.Unix(r.Stored, 0)) > s.ttl {
		return nil
	}
	return &r
}
